//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeeChartDemo.PCL.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeeChartDemo.PCL.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below left and right signal strength.
        /// </summary>
        internal static string BelowSignal {
            get {
                return ResourceManager.GetString("BelowSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current position.
        /// </summary>
        internal static string CurrentPosition {
            get {
                return ResourceManager.GetString("CurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to digital.
        /// </summary>
        internal static string DashDigital {
            get {
                return ResourceManager.GetString("DashDigital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exposure (fin$).
        /// </summary>
        internal static string DashExposure {
            get {
                return ResourceManager.GetString("DashExposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geographic.
        /// </summary>
        internal static string DashGeographic {
            get {
                return ResourceManager.GetString("DashGeographic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trend.
        /// </summary>
        internal static string DashTrend {
            get {
                return ResourceManager.GetString("DashTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δ avg.
        /// </summary>
        internal static string DeltaAverage {
            get {
                return ResourceManager.GetString("DeltaAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value $ 000s.
        /// </summary>
        internal static string DollarValue {
            get {
                return ResourceManager.GetString("DollarValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index of eu15.
        /// </summary>
        internal static string EUIndex {
            get {
                return ResourceManager.GetString("EUIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fixed.
        /// </summary>
        internal static string Fixed {
            get {
                return ResourceManager.GetString("Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexed.
        /// </summary>
        internal static string Indexed {
            get {
                return ResourceManager.GetString("Indexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InChart.
        /// </summary>
        internal static string LBGestureStyle1 {
            get {
                return ResourceManager.GetString("LBGestureStyle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullChart.
        /// </summary>
        internal static string LBGestureStyle2 {
            get {
                return ResourceManager.GetString("LBGestureStyle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string LBPoints1 {
            get {
                return ResourceManager.GetString("LBPoints1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to market cost index.
        /// </summary>
        internal static string MarketCost {
            get {
                return ResourceManager.GetString("MarketCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organic food consumption 2009.
        /// </summary>
        internal static string OrganicFood {
            get {
                return ResourceManager.GetString("OrganicFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participation %.
        /// </summary>
        internal static string Participation {
            get {
                return ResourceManager.GetString("Participation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        internal static string PivotItemAbout {
            get {
                return ResourceManager.GetString("PivotItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dashboard.
        /// </summary>
        internal static string PivotItemDashboard {
            get {
                return ResourceManager.GetString("PivotItemDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty.
        /// </summary>
        internal static string PivotItemEmpty {
            get {
                return ResourceManager.GetString("PivotItemEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series.
        /// </summary>
        internal static string PivotItemSeries {
            get {
                return ResourceManager.GetString("PivotItemSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        internal static string PivotItemSettings {
            get {
                return ResourceManager.GetString("PivotItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to themes.
        /// </summary>
        internal static string PivotItemThemes {
            get {
                return ResourceManager.GetString("PivotItemThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tools.
        /// </summary>
        internal static string PivotItemTools {
            get {
                return ResourceManager.GetString("PivotItemTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             TEECHART.NET FOR WINDOWS PHONE 8.
        /// </summary>
        internal static string PivotTitle {
            get {
                return ResourceManager.GetString("PivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private.
        /// </summary>
        internal static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public.
        /// </summary>
        internal static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recent movement.
        /// </summary>
        internal static string RecentMovement {
            get {
                return ResourceManager.GetString("RecentMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        internal static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steema Software has been providing developers with tools for charting since 1995. The TeeChart for Windows Phone .
        /// </summary>
        internal static string RunText1 {
            get {
                return ResourceManager.GetString("RunText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Library forms part of ongoing development making available for Phone .
        /// </summary>
        internal static string RunText2 {
            get {
                return ResourceManager.GetString("RunText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  application development all of the charting features that form part of the TeeChart Libraries. This preview application shows a few of the possibilities available to developers..
        /// </summary>
        internal static string RunText3 {
            get {
                return ResourceManager.GetString("RunText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sig. Frequency.
        /// </summary>
        internal static string SigFrequency {
            get {
                return ResourceManager.GetString("SigFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Data Points:.
        /// </summary>
        internal static string TextBlock1 {
            get {
                return ResourceManager.GetString("TextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesture Style:.
        /// </summary>
        internal static string TextBlock2 {
            get {
                return ResourceManager.GetString("TextBlock2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variable.
        /// </summary>
        internal static string Variable {
            get {
                return ResourceManager.GetString("Variable", resourceCulture);
            }
        }
    }
}
